In [17]:
import pandas as pd

cr = pd.read_csv("Outscraper-20260607153436s0a.csv")
imdb = pd.read_csv("IMDB Dataset SPANISH.csv")

print(cr.shape)
print(imdb.shape)

(500, 31)
(50000, 5)

In [18]:
cr = cr[[
    "review_text",
    "review_rating",
    "review_datetime_utc"
]].copy()

cr = cr.rename(columns={
    "review_text": "texto",
    "review_rating": "calificacion",
    "review_datetime_utc": "fecha"
})

cr = cr.dropna(subset=["texto"])

print(cr.shape)

cr.head()

(376, 3)

,texto,calificacion,fecha
1,An absolute money grab. Definitely not worth i...,1,06/06/2026 19:24:17
2,Love the hermit crabs!,5,06/06/2026 13:46:56
3,"Un lugar espectacular y, sin duda, una visita ...",3,06/06/2026 02:10:30
4,"El parque es espectacular, las 3 son porque es...",3,06/05/2026 21:24:50
5,Touristy and very overrated. Many other great ...,3,06/05/2026 05:46:47

In [23]:
def obtener_polaridad(rating):
    if rating >= 4:
        return "positivo"
    elif rating <= 2:
        return "negativo"
    else:
        return "neutral"


cr["polaridad"] = cr["calificacion"].apply(obtener_polaridad)

cr["tipo_lugar"] = "parque"
cr["fuente"] = "google_maps"

cr.head()

,texto,calificacion,fecha,polaridad,tipo_lugar,fuente
1,An absolute money grab. Definitely not worth i...,1,06/06/2026 19:24:17,negativo,parque,google_maps
2,Love the hermit crabs!,5,06/06/2026 13:46:56,positivo,parque,google_maps
3,"Un lugar espectacular y, sin duda, una visita ...",3,06/06/2026 02:10:30,neutral,parque,google_maps
4,"El parque es espectacular, las 3 son porque es...",3,06/05/2026 21:24:50,neutral,parque,google_maps
5,Touristy and very overrated. Many other great ...,3,06/05/2026 05:46:47,neutral,parque,google_maps

In [24]:
imdb = imdb[[
    "review_es",
    "sentimiento"
]].copy()

imdb = imdb.dropna(subset=["review_es"])

imdb = imdb.rename(columns={
    "review_es": "texto",
    "sentimiento": "polaridad"
})

imdb = imdb.head(1000)

imdb["calificacion"] = imdb["polaridad"].map({
    "positivo": 5,
    "negativo": 1
})

imdb["tipo_lugar"] = "dataset_respaldo"
imdb["fuente"] = "kaggle_imdb"
imdb["fecha"] = None

imdb.head()

,texto,polaridad,calificacion,tipo_lugar,fuente,fecha
0,Uno de los otros críticos ha mencionado que de...,positivo,5,dataset_respaldo,kaggle_imdb,None
1,Una pequeña pequeña producción.La técnica de f...,positivo,5,dataset_respaldo,kaggle_imdb,None
2,Pensé que esta era una manera maravillosa de p...,positivo,5,dataset_respaldo,kaggle_imdb,None
3,"Básicamente, hay una familia donde un niño peq...",negativo,1,dataset_respaldo,kaggle_imdb,None
4,"El ""amor en el tiempo"" de Petter Mattei es una...",positivo,5,dataset_respaldo,kaggle_imdb,None

In [25]:
columnas = [
    "texto",
    "calificacion",
    "polaridad",
    "tipo_lugar",
    "fuente",
    "fecha"
]

cr = cr[columnas]
imdb = imdb[columnas]

corpus_final = pd.concat(
    [cr, imdb],
    ignore_index=True
)

print(corpus_final.shape)

(1376, 6)

In [26]:
corpus_final.to_csv(
    "corpus_unificado_resenas.csv",
    index=False,
    encoding="utf-8-sig"
)

print("CSV generado correctamente")

CSV generado correctamente